import type { Metadata } from 'next';
import '@/styles/globals.css';
import { interFont, kumbhSansFont } from '@/constants/localFont';
import { AuthProvider } from '@/context/auth/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interFont.variable} ${kumbhSansFont.variable}`}>
      <body className={`antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
